[CS-4127] Updated UI for pin code creation
cardstack/cardwallet pull request #1009
Opened 2022-08-19 19:38 UTC by paulinhapenedo

### Description
This PR updates the PinScreen to match the new design guidelines:

- Removal of the subtitle
- Updated copy
- Title with the same style as the onboarding screens
- [x] Completes #CS-4127

### Checklist

- [x] Tested on a small device
- [x] Tested on iOS
- [x] Tested on Android

### Screenshots

### iOS
<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185694066-0a5d2470-3564-4bbf-9e97-a3e4358d8631.PNG">

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185694078-99aafc28-d0f5-4df6-af06-31e340038588.PNG">

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185694087-f8cf1597-1f09-4222-b2c5-96261397e645.PNG">

### Android with biometrics
<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185690909-4296635b-5101-4c8e-8d85-449ab6d2e5d4.jpg">

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185690915-44c547ea-6ae3-4328-aed7-cc9690e38ac5.jpg">

<img width="300" alt="Screenshot" src="https://user-images.githubusercontent.com/690904/185690917-805514b5-74b7-4056-93b3-f6bfbc434532.jpg">

2022-08-22 16:19 UTC, danibonilha commented on cardstack/src/screens/PinScreen/strings.ts
> -  },
Not sure if we should remove the subtitle, what if we use the style like the restore, to have the title on top, and then the subtitle with a smaller font ? 

something like: 
<img width="272" alt="image" src="https://user-images.githubusercontent.com/20520102/185969305-2b22038b-fa2c-4c54-a4af-c9a1bae61bcc.png">

but then the copy being, Create PIN ---- Please choose a pin to protect your wallet on this device. We could also ask for copy for the other flows

2022-08-22 16:19 UTC, danibonilha commented on cardstack/src/screens/PinScreen/PinScreen.tsx
> +            {strings.flow?.[flow]}
The layout doesn't seem correct, in my understanding the title should be closer to the back button, and not almost centered as is.

2022-08-22 16:20 UTC, danibonilha commented on cardstack/src/screens/PinScreen/strings.ts
> -    subtitle: `Please enter yout new PIN for your ${appName}`,
if we were to keep these specific subtitles, there's a typo here, `yout`

2022-08-22 18:09 UTC, oidoug commented on cardstack/src/screens/PinScreen/PinScreen.tsx
> +            {strings.flow?.[flow]}
We should match the spacing we used for profile creation, even though it'll leave more empty space between title and the input boxes.

2022-08-22 19:10 UTC, paulinhapenedo commented on cardstack/src/screens/PinScreen/PinScreen.tsx
> +            {strings.flow?.[flow]}
## Android

<img src="https://user-images.githubusercontent.com/690904/185999170-a10b8cb1-93db-40ec-b773-b3b4b989b7a2.jpg" width="350" />

<img src="https://user-images.githubusercontent.com/690904/185999180-cf7ed564-808f-4a49-83a7-21a65ce77b77.jpg" width="350" />

<img src="https://user-images.githubusercontent.com/690904/185999183-83640f5c-d298-4835-bc64-e06971d1eed6.jpg" width="350" />


## iOS

<img src="https://user-images.githubusercontent.com/690904/185999663-ad2871f9-ee5f-4a05-9b57-5db2f9839c3b.png" width="350" />

<img src="https://user-images.githubusercontent.com/690904/185999667-1ba98402-9a44-4f14-87ee-e84d4f2b443c.png" width="350" />

<img src="https://user-images.githubusercontent.com/690904/185999798-90031d8b-40bd-46c5-8892-7806dfa584cd.png" width="350" />

cc @oidoug @danibonilha

2022-08-22 19:35 UTC, oidoug commented on cardstack/src/screens/PinScreen/PinScreen.tsx
> +            {strings.flow?.[flow]}
Looks like your android sim has a massive screen 😂 
may look strange, but it's more consistent this way.

2022-08-22 19:37 UTC, oidoug approved these changes
LGTM

2022-08-22 20:10 UTC, danibonilha requested changes
The alignment with the pinInput is a bit off, specially on iPhone SE,  this is what we have today: 
<img width="300" alt="image" src="https://user-images.githubusercontent.com/20520102/186009686-2d21c290-1c03-48c4-88db-7d35eca0bf92.png">
We should aim to keep the spacing consistent in the input, and it feels more natural to have the back button aligned with the boxes, if we had the smalller input, then it would make sense to have different alignments

2022-08-23 13:01 UTC, oidoug requested changes
Looking more carefully now I see the paddings for the input are a bit strange, too clumped together.

now:
<img width="300" src="https://user-images.githubusercontent.com/129619/186162609-3a1eec48-1e5d-4e58-bb72-7a74155ccfc4.jpg">

before:
<img width="300" src="https://user-images.githubusercontent.com/129619/186164319-29bcb180-06bd-49e8-83d2-e21cd2cd7f45.jpg">

I approved it before on account that this change is a bit complex to get it right. We are mix-matching old and new designs, we'll have to get back to this after we do a design review.

Easiest to do now is to just focus on the title but without changing how the input renders, keeping its original paddings.

2022-08-23 19:18 UTC, danibonilha approved these changes
LGTM

2022-08-23 19:18 UTC, danibonilha commented on cardstack/src/screens/PinScreen/PinScreen.tsx
> +
nit: no need for new line

2022-08-23 20:45 UTC, oidoug approved these changes
Looking good now 🚀

2022-08-23 20:46 UTC, merged