Reward claim step over
cardstack/cardwallet pull request #1020
Opened 2022-08-26 06:02 UTC by tintinthong

### Description

- [ ] Completes #(Linear ticket)

### Checklist

- [ ] Tested on a small device
- [ ] Tested on iOS
- [ ] Tested on Android

### Screenshots

2022-08-26 14:06 UTC, oidoug approved these changes
This PR covers all cases described in card 4445 (https://linear.app/cardstack/issue/CS-4445/handle-crypto-dust-rewards-in-mobile-app) except the point 2. Rewards badge should not display as active if user only has dust.

If you prefer we can handle that specifically in a new ticket after this one is merged.

I think it's clear to merge once SDK is updated and lint issues resolved.

2022-08-26 14:06 UTC, oidoug commented on cardstack/src/screens/RewardsCenterScreen/components/ClaimContent.tsx
> +          showClaimBtn={item.showClaimBtn}
nit: Instead of adding a new prop you could pass undefined to `onClaimPress` if `item.showClaimBtn` is false.

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +  } = useGetRewardPoolTokenBalancesQuery(dustQuery.params, dustQuery.options);
instead of creating the `dustQuery` we can reuse the `query` object here, just adding the missing param: 
```tsx
useGetRewardPoolTokenBalancesQuery(
    { ...query.params, safeAddress: rewardSafes?.[0].address },
    query.options
  );
```

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
>    // Checks if available tokens matches default program and has amount
we should remove the last piece of this comment, since there's no amount check anymore

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +    claimSheetTokenInfo,
I believe mainPoolTokenInfo and claimSheetTokenInfo are a bit confusing now,  we could rename those to reflect their purposes, `mainPoolTokenInfo  => fullBalanceToken` and `claimSheetTokenInfo => claimableBalanceToken`

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/RewardsClaimSheet/useRewardsClaim.ts
> +  const mainPoolTokenRef = useRef(claimSheetTokenInfo);
we should change the name of this ref to match the used variable

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +  const canClaimAll = !!claimSheetTokenInfo;
Is just checking `!!claimSheetTokenInfo` existence enough ?  Isn't it safer to check `!!claimSheetTokenInfo.balance`  in case claimSheetTokenInfo is an empty array, using `!!claimSheetTokenInfo'  will return true.


1. Instead of having this prop here and then passing down to token balances, we could add this to `mainPoolTokenInfo` (soon to be ) `fullBalanceToken`: 
```tsx
  const fullBalanceToken = useMemo(() => {
    const balances = rewardPoolTokenBalances?.find(
      ({ rewardProgramId }) => rewardProgramId === defaultRewardProgramId
    );

    return { ...balances, isClaimable: !!claimableBalanceToken.balance };
  }, [rewardPoolTokenBalances, claimableBalanceToken, defaultRewardProgramId]);
  ```

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/RewardsCenterScreen.tsx
> +      showClaimBtn: canClaimAll,
1.1 then here, you replace showClaimBtn with `isClaimable:  mainPoolTokenInfo?.isClaimable`

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/components/RewardRow.tsx
> +      {!!onClaimPress && showClaimBtn && (
1.3 this change could be dropped

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsCenterScreen.ts
>    };
1.4 this one too

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/components/ClaimContent.tsx
> +          showClaimBtn={item.showClaimBtn}
1.2 then here you could have:
```ts
  onClaimPress={item.isClaimable ? onClaimPress : undefined}
```

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/services/gnosis-service.ts
> +  const tokenBalance = acceptDust ? balance : isAmountDust ? 0 : balance;
we could simply this with:
```ts
  const isAmountDust = !acceptDust && nativeBalance < 0.01;

  const amount = isAmountDust ? 0 : nativeBalance;

  const tokenBalance = isAmountDust ? 0 : balance;
```

2022-08-26 14:43 UTC, danibonilha commented on cardstack/src/services/rewards-center/rewards-center-service.ts
> +    totalEstimatedGas[0].amount.toString()
Does `claimAllGasEstimate`  returns a array ? I'm a bit confused by `totalEstimatedGas[0].amount`

2022-08-26 14:44 UTC, danibonilha requested changes
Adding the changes request just to avoid merging, before sdk and ci issues are fixed

2022-08-26 15:00 UTC, danibonilha commented on cardstack/src/services/rewards-center/rewards-center-service.ts
> +  console.log(accountAddress);
leftover console.log

2022-08-26 15:42 UTC, tintinthong commented on cardstack/src/services/rewards-center/rewards-center-service.ts
> +    totalEstimatedGas[0].amount.toString()
Right. I should have left a comment here. This is related to an SDK change. 

So `claimAllGasEstimate` derives estimates from all proofs. But our proofs can have different tokens. And `gasToken` is paid in whatever tokens (either dai or card). So what I did was return an array becuase u can have `[GasEstimateCardToken, GasEstimateDaiToken, GasEstimateNewGasToken]`. 

Now the SDK only accepts `GasEstimateCardToken` but I didn't want to force myself into making assumptions on what tokens the proofs are. But I guess this has forced me into taking the first element and assuming this is card token for now. 

Perhaps, I should add a comment???

2022-08-26 15:54 UTC, tintinthong commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +  } = useGetRewardPoolTokenBalancesQuery(dustQuery.params, dustQuery.options);
im not too certain how react works. 

`useMemo` seems to take a list of dependencies one of which is `rewardSafes`. I assumed the cached value will change dependening on if `rewardSafes` is available. Which is why I made another query.

2022-08-26 17:55 UTC, danibonilha commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +  } = useGetRewardPoolTokenBalancesQuery(dustQuery.params, dustQuery.options);
The common way to passing params to those queries, are inline objects, for this hook specifically we are using memo, because multiple queries needed the same params, and options.

2022-08-26 19:15 UTC, tintinthong commented on cardstack/src/screens/RewardsCenterScreen/useRewardsDataFetch.ts
> +  } = useGetRewardPoolTokenBalancesQuery(dustQuery.params, dustQuery.options);
ok. Was just wondering that `dustQuery` uses rewardSafe as a dependency which is non-existent in `query`. But even after removal I have not seen any changes to the output.

2022-08-28 19:48 UTC, tintinthong commented
I fixed bug here [17b7884](https://github.com/cardstack/cardwallet/pull/1020/commits/17b788490c2d2eaf4fec9066f50882367403eaf9) and improved the fix same bug fix here [476593c](https://github.com/cardstack/cardwallet/pull/1020/commits/476593c7473364fcaf56adaa84624931ae2e7c75)

2022-08-29 13:01 UTC, oidoug reviewed
I have nothing new to add.

2022-08-29 13:40 UTC, danibonilha approved these changes
Looks good to go

2022-08-29 13:56 UTC, merged