[CS-4667] Handle cloud backup deletion
cardstack/cardwallet pull request #1063
Opened 2022-10-04 22:12 UTC by paulinhapenedo

### Description
Opening this as a draft to have the team's eyes on it.
Still gonna add tests to the `useWalletCloudBackup` and test it on iOS.

- [ ] Completes #CS-4667

### Checklist

- [x] Tested on a small device
- [ ] Tested on iOS
- [x] Tested on Android

### Screenshots

TBD

2022-10-07 12:51 UTC, oidoug approved these changes
LGTM 🔥 
I only have one comment you can address before merging.

2022-10-07 12:51 UTC, oidoug commented on src/redux/wallets.js
> +  await dispatch(walletsSetSelected(wallets[selected.id]));
It makes sense to always update the selected wallet. But I think you missed removing the call to `walletsSetSelected` at line 144, as you did in 161 and 292.

2022-10-07 13:01 UTC, oidoug requested changes
While testing I noticed that after deleting the backup, the Recovery Phrase screen opened from settings doesn't update, it still shows the "delete icloud backup" button.

2022-10-07 13:55 UTC, danibonilha commented on src/components/settings-menu/DeveloperSettings.js
> +import { deleteCloudBackups } from '@cardstack/hooks';
This function don't seem to exist outside a hook

2022-10-07 13:55 UTC, danibonilha commented on src/hooks/useManageCloudBackups.ts
>        }
nit: we don't seem to need the `deleteWalletWithConfirmation` on this hook anymore, it could be replaced with the new `deleteCloudBackups` from useWalletCloud hook

2022-10-07 14:12 UTC, paulinhapenedo commented on src/hooks/useManageCloudBackups.ts
>        }
This hook will be deleted.

2022-10-10 16:55 UTC, oidoug approved these changes
All good! 🛸

2022-10-10 17:28 UTC, merged