[CS-1550] Refactor Prepaid card component, fix bug with rendering pattern
cardstack/cardwallet pull request #296
Opened 2021-08-08 13:21 UTC by topwebtek7

![image](https://user-images.githubusercontent.com/16714648/128633380-d49e7ef1-bf36-45a9-8a23-054339dbd093.png)

2021-08-08 14:11 UTC, lukemelia requested changes

2021-08-08 14:11 UTC, lukemelia commented on cardstack/src/types/transaction-types.ts
> +
This file is called `transaction-types`. Let's make it contain only transaction types and introduce a new file for `prepaid-card-types` or maybe `customization-types`.

2021-08-08 14:11 UTC, lukemelia commented on cardstack/src/utils/cardpay-utils.ts
> +};
This would be a terrific function to have unit tests for!

2021-08-08 14:14 UTC, topwebtek7 commented on cardstack/src/utils/cardpay-utils.ts
> +};
ok, agreed. will write tests for it.

2021-08-10 07:10 UTC, lukemelia commented on cardstack/src/utils/__tests__/cardpay-util.test.ts
> +});
I suggest adding a test case with an unsupported variation. e.g. radial-gradient and/or 3 stop linear gradient so that the failure mode is well-understood.

2021-08-10 07:12 UTC, topwebtek7 commented on cardstack/src/utils/__tests__/cardpay-util.test.ts
> +});
ok, good point.

2021-08-10 19:03 UTC, danibonilha approved these changes
LGTM

2021-08-11 03:50 UTC, lukemelia approved these changes
🦖  Looks good!

2021-08-11 04:29 UTC, merged