[CS-1592] Refactor transactions mapping to use strategies
cardstack/cardwallet pull request #305
Opened 2021-08-12 19:57 UTC by topwebtek7

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-13 at 03 47 51](https://user-images.githubusercontent.com/16714648/129261153-a88078fb-88fd-49de-b575-3883f94dd265.png)

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-08-13 at 03 47 22](https://user-images.githubusercontent.com/16714648/129261147-077c7df4-5a19-4998-8b4e-65dc03593117.png)

2021-08-13 05:16 UTC, lukemelia requested changes
Nice application of the strategy pattern 👍  Left a couple of suggestions.

2021-08-13 05:16 UTC, lukemelia commented on cardstack/src/transaction-strategies/context.ts
> +export class TransactionContext {
Consider renaming to something like TransactionMappingContext, and corresponding directories as well. I think the name needs a verb, to describe the action it is responsible for. A comment in this file describing the purpose would be helpful, too.

2021-08-13 05:16 UTC, lukemelia commented on cardstack/src/transaction-strategies/context.ts
> +          return null;
Do we expect some transactions to have no strategy that handles them? If not, should we log an error to Sentry here?

2021-08-13 13:25 UTC, topwebtek7 commented on cardstack/src/transaction-strategies/context.ts
> +          return null;
Updated with more meaningful names and corresponding directories, added sentry logs when no strategy that handles transaction

2021-08-13 14:17 UTC, DominicSherman approved these changes
Just a few comments, looks good!

2021-08-13 14:17 UTC, DominicSherman commented on cardstack/src/transaction-strategies/transaction-mapping-strategy-types/bridge-to-layer1-strategy.ts
> +    const bridgeToLayer1Events = this.transaction.bridgeToLayer1Events?.[0];
Should this be `bridgeToLayer1Event` since it's a single item?

2021-08-13 14:17 UTC, DominicSherman commented on cardstack/src/transaction-strategies/transaction-mapping-strategy-types/bridge-to-layer2-strategy.ts
> +    const bridgeToLayer2Events = this.transaction.bridgeToLayer2Events?.[0];
Same thing here

2021-08-13 14:17 UTC, DominicSherman commented on cardstack/src/transaction-strategies/transaction-mapping-strategy-types/erc20-token-strategy.ts
> +    if (tokenTransfers?.length) {
One thing we need to be sure of is that there aren't other fields on here. I _think_ most transactions have token transfers on them. We'll either need to make sure we check this last or add prelim checks to ensure this isn't any other transaction type

2021-08-13 14:17 UTC, DominicSherman commented on tsconfig.json
> +        "cardstack/src/transaction-strategies"
Should we update this directory to be `transaction-mapping-strategies`?

2021-08-13 15:10 UTC, topwebtek7 commented on cardstack/src/transaction-strategies/transaction-mapping-strategy-types/erc20-token-strategy.ts
> +    if (tokenTransfers?.length) {
yeah, good point. will make sure to check token transfer at the end

2021-08-13 15:19 UTC, topwebtek7 commented on cardstack/src/transaction-strategies/context.ts
> +export class TransactionContext {
@lukemelia updated directories and names, added helpful comments as well

2021-08-15 08:06 UTC, lukemelia approved these changes
👍

2021-08-15 08:08 UTC, merged