[WIP] - Show merchant earned txn Account Details
cardstack/cardwallet pull request #348
Opened 2021-09-02 14:18 UTC by eshinkawa

### Description

- [ ] Completes #(Linear ticket)

### Checklist

- [ ] All UI changes have been tested on a small device

### Screenshots

2021-09-05 01:42 UTC, eshinkawa commented
I apologize for the amount of code, but they tackle two tickets

2021-09-06 00:35 UTC, eshinkawa commented
I apologize for the amount of code, but they tackle two tickets and they're dependent of each other

2021-09-06 14:57 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        }
Let's keep the `onPressTransaction` function, wrap it with an useCallback and handle the condition based on `toTransactionDetails` there

2021-09-06 16:07 UTC, danibonilha requested changes

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        }
Let's add a  `handleOnPressTransaction` function, wrap it with an useCallback and handle if we have the `onPressTransation` function from props to be called, otherwise we default to `showBlockscout`

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +
We should properly type this

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        ) : null}
Actually I don't think we should check for address to render this, `PrepairdCard`, for example, have an address, and since this is used on different places, it affects others components, as you can see is double showing the address: 
<img src="https://user-images.githubusercontent.com/20520102/132238019-2ca019d1-4a83-4695-9b82-114464ef68d4.png"  width="300">

We should probably use the `Header` prop from `TransactionBase`, 
also the address needs to be obfuscated, we use `getAddressPreview` to handle that

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +  toTransactionDetails?: any;
isn't this a function?  If we don't know the prop types we should probably use a generic type, also maybe this should be called  `onPressTransaction`, because what's is navigating to transaction details, is your function in the parent, so the tx item doesn't need to know what happens onPress

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/utils/__tests__/merchant-utils.test.ts
>  });
👏

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/utils/merchant-utils.ts
> +  merchantClaimTransaction: any,
Don't we have a type for that ?

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/utils/merchant-utils.ts
> +): any {
let's avoid using any as much as possible, in expectation for when we are dealing with ts to js stuff, if is something really hard to figure, we can spend some time together in it, or add a TODO to properly type

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/types/transaction-types.ts
> +  transaction?: any;
ditto

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/utils/merchant-utils.ts
> +  if (!merchantClaimTransaction || !address) return null;
Should we return `undefined` instead of `null`, since `transaction` is typed as a optional, which means that, it's either that type or `undefined`

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/utils/merchant-utils.ts
> +  if (!prepaidCardPaymentTransaction) return null;
ditto

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +  };
We can move those components outside the main component, at least the ones that receives params which will make the code cleaner and we will avoid recreating those components on every re-render or we can wrap in useMemos

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +        onPress={() => Linking.openURL(`${blockExplorer}/tx/${normalizedHash}`)}
Let's avoid using anonymous functions on render, if we create a component for this, we can even use the normalizedHash only there to keep the context

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +        />
nit: Thinking about how many ItemDetail we are using, maybe we can have a data structure, were we just loop over and render a itemDetail

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +}
We can't actually see the BlockscoutButton, and if we try to scroll up, the modal get's back down, and we can't click on it

2021-09-06 16:07 UTC, danibonilha commented on cardstack/src/components/Transactions/MerchantClaimTransaction.tsx
> +
We should double check this behavior, because while navigating to Transaction details, we cannot get back to the activities list, I think we should have a modal on top the other, or a back button, whatever it's easier, I noticed rainbow has it's own useNavigation, not sure though if it impacts this

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +}
Should everything be optional ? If we don't have any of those properties, why render itemDetail ? at least description should be required

2021-09-06 16:07 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +export default function MerchantTransactionExpandedState(props: any) {
ditto

2021-09-06 16:37 UTC, eshinkawa commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        ) : null}
Right! This was a nice to have for the ticket, but it will need a bigger discussion, so I am adding a TODO for it

2021-09-06 23:06 UTC, eshinkawa commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +}
yes, I talked to Kiel about, since this gonna impact other screens so I will keep the way things currently are for the next discussions!

2021-09-07 12:39 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        }
sorry I think I didn't explained my idea correctly, here I'm suggesting that we have:
```tsx
const handleOnPressTransaction = useCallback(() => {
         onPressTransaction ? onPressTransaction(props) : onPressBlockscout
} ,[onPressTransaction])
```
then we use this handleOnPress, on this Touchable onPress

2021-09-07 12:39 UTC, danibonilha commented on cardstack/src/components/Transactions/TransactionBase.tsx
> +        */}
we should remove this entirely and take `TransactionBase` as an example, if we want to create a new component that will have a specific header, and specific footer, we can just do something like it and if this is just for the merchant flow, it doesn't need to be related to TransactionBase

2021-09-07 12:39 UTC, danibonilha commented on cardstack/src/utils/merchant-utils.ts
> +};
I think we can move this to `BlockscoutButton`

2021-09-07 12:39 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +          />
if we move the link inside this Button the only prop we need to pass is a transaction

2021-09-07 12:39 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +};
```suggestion
const BlockscoutButton = ({
  transactionHash,
}: {
  transactionHash: string;
}) => {
const onPress = useCallback(() => {
  const blockExplorer = getConstantByNetwork('blockExplorer', network);
  const normalizedHash = normalizeTxHash(transactionHash);

  Linking.openURL(`${blockExplorer}/tx/${normalizedHash}`);
}, [transactionHash]);  

  return (
    <Button
      marginBottom={12}
      onPress={onPress}
      variant="smallWhite"
      width="100%"
    >
      View on Blockscout
    </Button>
  );
};
```

2021-09-07 12:39 UTC, danibonilha commented on src/components/expanded-state/UnclaimedRevenueExpandedState.tsx
> +);
I believe we need to revert this change, because it makes sense to use `<ListEmptyComponent text="No activity" />`since the component already exists

2021-09-07 21:28 UTC, danibonilha approved these changes
If the scroll is working properly, we can ship it  🚀

2021-09-07 21:28 UTC, merged