Upgrade reanimated and fix animation issues
cardstack/cardwallet pull request #352
Opened 2021-09-03 18:45 UTC by topwebtek7

### Description

2021-09-14 13:36 UTC, danibonilha requested changes
It's crashing when we tap on assets in the main screen, also inside depots, basically every place that is using ChartExpandedState

2021-09-14 13:38 UTC, danibonilha commented on scripts/postinstall.sh
> +rm -rf node_modules/react-native-udp/ios/CocoaAsyncSocket
EOF

2021-09-15 13:30 UTC, topwebtek7 commented
> It's crashing when we tap on assets in the main screen, also inside depots, basically every place that is using ChartExpandedState

Resolved this crash issue

2021-09-21 14:43 UTC, danibonilha requested changes
It's crashing still =/ . if you open a chart, close it and then open another one, it crashes, plus the chart is a bit funky while sliding through values

2021-09-23 11:38 UTC, topwebtek7 commented
> It's crashing still =/ . if you open a chart, close it and then open another one, it crashes, plus the chart is a bit funky while sliding through values

Resolved crash issue. It looks ok to be merged now but please review again

2021-09-23 13:31 UTC, danibonilha reviewed
Send flow crashed

![image](https://user-images.githubusercontent.com/20520102/134514038-51fb8081-9962-4890-9c75-c1967e6a9006.png)

Seems related to useTimingTransition

2021-09-23 13:35 UTC, danibonilha commented on src/components/animations/RoundButtonSizeToggler.js
> +import { bin, useSpring as useSpringTransition } from 'react-native-redash';
If the API has changed, maybe it's better to use the new method name instead of casting to the old value, so we won't forget to remove all old name's api, f.e we can search for `useSpringTransition`  in the whole project and make sure we got rid of all occurrences, bc the search will have 0 results

2021-09-23 15:13 UTC, topwebtek7 commented on src/components/animations/RoundButtonSizeToggler.js
> +import { bin, useSpring as useSpringTransition } from 'react-native-redash';
@danibonilha resolved crash issue, please check it again

2021-09-28 09:30 UTC, closed without merging