[WIP] Add enter amount for merchant payment screen
cardstack/cardwallet pull request #365
Opened 2021-09-09 08:15 UTC by topwebtek7

### Description

 Added enter amount for merchant payment screen and working on global currency selection component

- [ ] Completes #(Linear ticket)

### Checklist

- [ ] All UI changes have been tested on a small device

### Screenshots

2021-09-13 20:05 UTC, danibonilha requested changes
It's not working as expected,
- changing the currency, changes the entire app currency and it doesn't reflect in the input currency button, it's always SPD
- the component has some unnecessary re-renders, which refetches merchantInfo and re-checks for no prepaid cards.
- Clicking next goes to the confirmation and we have no way to get back
- Deleting the input value crashes the app
- Using this as a native stack if the app is closed and the click on the link to open it up we get stuck on this screen, without any merchant info, nor screens at the bottom

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Icon/custom-icons/doubleCaret.tsx
> +export default DoubleCaretSvgComponent;
nit: FYI, for svgs that does not require any modification we can use the Svgxml components and just render with the svg string, for example: https://github.com/react-native-svg/react-native-svg#use-with-xml-strings, this way we don't need to convert anything

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Input/InputAmount.tsx
> +        justifyContent="center"
We have the CenteredContainer

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Input/InputAmount.tsx
> +            {(supportedNativeCurrencies as any)[nativeCurrency].symbol}
Wondering if instead of using this as a json we should either transform it to a object, or handle this as we would handle an api response

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Input/InputAmount.tsx
> +            multiline
Do we want multiple for this ?

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Input/InputAmount.tsx
> +            }}
```suggestion
            onPress={openCurrencySelectionModal}
```

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/Text/EmojiText.tsx
> +};
What is this for ? it seems it's not being used anywhere

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +      {inputValue && (
This needs to be cast to boolean, otherwise it will crash

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/navigation/hooks.tsx
> +  screens: Record<string, { component: any; options?: StackNavigationOptions }>,
I believe we have a type for this in the screens file

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +  const [selectedCurrency, setCurrency] = useState<string>('SPD');
Should this default to what we receive from the link ? Also the supported currencies json doesn't have SPD how are we planning to deal with that ?

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/CurrencySelectionGlobalModal.tsx
> +      width="100%"
we don't need this

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/CurrencySelectionGlobalModal.tsx
> +        <Container width="100%" alignItems="center" padding={5}>
don't need the width also

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +        />
I think we need to align with design, but this should be it's own screen, imagine I entered an amount hit next, and then I realized, oh the amount is wrong, how can I go back to the enter amount screen if now it's this confirmation screen ? I'll need to get the link again, and start the whole flow

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +          width="100%"
don't need width

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +  setInputValue: (_val: string | undefined) => void;
we could probably have an interface with this and extends thru the components

2021-09-13 20:05 UTC, danibonilha commented on cardstack/src/components/CurrencySelection/CurrencySelection.tsx
> +  );
We shouldn't be using nativeCurrency here, because even if I want to change the currency for this specific payment, it doesn't mean that I want to change for the whole application

2021-09-14 03:36 UTC, topwebtek7 commented on cardstack/src/components/Input/InputAmount.tsx
> +            multiline
yes we need according to the design

2021-09-14 03:40 UTC, topwebtek7 commented on cardstack/src/components/CurrencySelection/CurrencySelection.tsx
> +  );
yea, was trying to find a workaround for it.. as we change currency in another modal, it's not easy to change for this specific payment

2021-09-14 06:49 UTC, topwebtek7 commented on cardstack/src/components/Icon/custom-icons/doubleCaret.tsx
> +export default DoubleCaretSvgComponent;
we need to update size so created svg component

2021-09-14 06:51 UTC, topwebtek7 commented on cardstack/src/components/Input/InputAmount.tsx
> +            {(supportedNativeCurrencies as any)[nativeCurrency].symbol}
we will fetch this from sdk in next change, worked on it with Michael to be consistent with dapp

2021-09-14 06:56 UTC, topwebtek7 commented on cardstack/src/screens/PayMerchant.tsx
> +        />
there's edit amount button according to design update and I thought this flow would be more easy to go back and edit amount and re-confirm.

2021-09-15 12:54 UTC, danibonilha requested changes
Couple of things are still not working as expected: 
Major: The request is done with the link amount instead of the edited amount, the comment have more context.
Minor: Selection a currency in the modal only works on second tap.

Since we are implementing the currency selector in this PR, we should probably change the way the merchant link is being created, it's defaulting to Spend, so if the user changes the currency in the request payment, when the other user tries to pay the currency will be wrong, and it will be confusing

2021-09-15 12:54 UTC, danibonilha commented on cardstack/src/components/Icon/custom-icons/doubleCaret.tsx
> +export default DoubleCaretSvgComponent;
But we can change size with that too, when I said modifications, I meant, conditionally rendering a <Path> for example, or animating an svg component, but this way is fine to, just thought you'd like to know there's more than one way =)

2021-09-15 12:54 UTC, danibonilha commented on cardstack/src/redux/payment.ts
> +};
Since we are talking about moving away from redux, I don't think understand the need to create this, since the currency selection screen can just receive a callback and return the selected currency, even if we need to share it globally  we could use context instead of redux, but taking into consideration the value of the feature, we can let this pass and revisit this implementation to remove redux.

2021-09-15 12:54 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +});
nit: we could wrap the anonymous functions with useCallback

2021-09-15 12:54 UTC, danibonilha commented on cardstack/src/screens/PayMerchant.tsx
> +        <Button onPress={goToConfirm}>
nit: This is called `goToConfirm` but it actually doesn't do that, it does what the parent says, which is go to confirm, so this probably should be called `onNextPress`, or `onButtonPress` and in the parent, the callback could be goToConfirm and setConfirmScreen

2021-09-15 12:54 UTC, danibonilha commented on src/navigation/Routes.ios.js
> +  const cardstackMainScreens = useCardstackMainScreens(Stack);
This change needs to be applied to `Routes.android too`, search for `useCardstackScreens`

2021-09-15 12:54 UTC, danibonilha commented on cardstack/src/hooks/merchant/usePaymentMerchantUniversalLink.ts
>    } = useRoute<RouteType>();
Since we are not navigating and this is being extract from the navigation, the first value from the link remains, for example, if my link says it's 300 spend, and I change in `PayMerchant` to 2 spend, the UI will say 2, but the request will be made with 300 spend because it never changed.
So we need to change this implementation, we could either move this from `usePaymentMerchantUniversalLink` and use in `PayMerchant` or in `PayMerchant` once we change the amount or currency, we update the nav params with it.

2021-09-15 13:04 UTC, topwebtek7 commented on cardstack/src/redux/payment.ts
> +};
Personally we can optimize current redux as current redux is not well structured, but i don't think using context is not a great idea.. yeah we can revisit and discuss this later

2021-09-16 04:45 UTC, topwebtek7 commented
@danibonilha can you review?

2021-09-16 13:09 UTC, danibonilha approved these changes
The generated merchant url is not being handled yet, but we can probably do this on a different PR, since we will get from sdk.

2021-09-16 13:13 UTC, topwebtek7 commented
> The generated merchant url is not being handled yet, but we can probably do this on a different PR, since we will get from sdk.

Yep we have another ticket for that and planning to do that next week monday

2021-09-16 13:13 UTC, merged