[CS-1838][CS-1900] - Handle deep link when app is closed and update info
cardstack/cardwallet pull request #388
Opened 2021-09-24 14:31 UTC by danibonilha

### Description
We have nested navigators and although the previous config seemed correct because it was working when app was open, once it's closed it doesn't know where to go, plus when it's closed we don't have the prepaidCards and stuff ready yet when we go to the screen, so this PR:

- Opens app on right screen when it's closed 
- Adds loading on deep link cold start, to get redux data, there's a workaround with fake loading (open to suggestions if anyone has a better idea), because on first render prepaidcards are empty
- With the right link path, now we can use the `Linking.openUrl` to handle the QRcode
- Added hepatics when QR code is recognized

- [x] Completes #(CS-1838)
- [x] Completes #(CS-1900)

### Screenshots

Open QR code app closed:
![pay-merchant-close](https://user-images.githubusercontent.com/20520102/134691372-3746fad8-c3cf-497f-9e57-63735a5cf0b8.gif)
Open a different QR code:
![pay-merchant-update](https://user-images.githubusercontent.com/20520102/134691395-0a880d9d-c4f9-4e35-8205-6d3c395b5c1c.gif)

2021-09-24 17:17 UTC, topwebtek7 requested changes
Overall this PR's looks good to me and great job! 👍🏼 
Just small comment and suggestion

2021-09-24 17:17 UTC, topwebtek7 commented on cardstack/src/hooks/merchant/usePaymentMerchantUniversalLink.ts
> +    isLoading: isLoading && fakeLoading,
not sure but does it should be like `isLoading || fakeLoading`?

2021-09-24 17:17 UTC, topwebtek7 commented on cardstack/src/hooks/merchant/usePaymentMerchantUniversalLink.ts
> +  }, []);
I think there's no guarantee prepaidcards can be loaded in 2 seconds.. 
IMO, we can watch `isLoadingAssets` change from false to true if no prepaidcards
`isLoadingAssets=true` means fetching prepaidCards are finished.

we can get isLoadingAssets like below.
```
const { isLoadingAssets } = useAssetListData();
```

2021-09-24 20:37 UTC, danibonilha commented on cardstack/src/hooks/merchant/usePaymentMerchantUniversalLink.ts
> +  }, []);
You're right, didn't know we had a loading prop for that, I thought this prop was always loading because of fallbackExplorer, thanks

2021-09-24 22:31 UTC, eshinkawa approved these changes

2021-09-25 05:57 UTC, topwebtek7 approved these changes
LGTM! 🚢

2021-09-25 15:37 UTC, merged