[CS-2504] - Update Merchant Balances to look like depot balance
cardstack/cardwallet pull request #506
Opened 2021-11-15 19:54 UTC by eshinkawa

### Description

Merchant balances are confusing to end users and not clear they can be drilled into; Update Merchant Balances to look like depot balance.

I moved the **<Balances />** component to the component folder so it would be reusable for both Depot and Merchant screens.

- [X] Completes #2504

### Checklist

- [X] All UI changes have been tested on a small device

### Screenshots

![Nov-15-2021 16-53-10](https://user-images.githubusercontent.com/8547776/141845210-a88e6c6c-2d24-4c7b-bffa-0bc64cda25e9.gif)

2021-11-16 04:25 UTC, lukemelia reviewed
How about a little test coverage for this newly moved component?

2021-11-16 12:28 UTC, danibonilha requested changes
The wrong information is being displayed, more info on my comment

2021-11-16 12:28 UTC, danibonilha commented on src/components/expanded-state/AvailableBalancesExpandedState.tsx
> +  const tokensData = depots?.[0].tokens;
We should have the same UI as depots on merchant balances, but not the same information, we need to use the tokens balances from the selected merchant safe and not from depot. Merchant, PrepaidCard and Depot they are all different types of safes and should not mix its contexts.

2021-11-16 12:28 UTC, danibonilha commented on cardstack/src/components/Balances/Balances.tsx
> +export const Balances = ({ tokens }: BalancesProps) => {
We could rename this to BalanceSection or so, only Balances does not tell much

2021-11-16 20:15 UTC, danibonilha commented on src/components/expanded-state/AvailableBalancesExpandedState.tsx
> -            safeAddress,
Here we are passing the `safeAddress` as a nav param, so we can get the merchantSafea address in order to send the tokens from merchant, this is missing in the new BalancesSection, thus while trying to send tokens from merchant, the tokens from depot will be sent instead

2021-11-16 20:15 UTC, danibonilha commented on cardstack/src/components/BalanceSection/BalanceSection.tsx
> +        type: 'token',
Missing the safeAddress param

2021-11-16 21:07 UTC, eshinkawa commented on cardstack/src/components/BalanceSection/BalanceSection.tsx
> +        type: 'token',
i passing as optional params, see what you think @danibonilha

2021-11-17 15:11 UTC, danibonilha approved these changes

2021-11-17 15:12 UTC, danibonilha commented on cardstack/src/components/BalanceSection/BalanceSection.tsx
> +        ...navProps,
It doesn't really need to be optional, ideally we can pass the safeAdress from depot too, we didn't do it before, because it used to default just depot transactions

2021-11-17 18:59 UTC, eshinkawa commented on cardstack/src/components/BalanceSection/BalanceSection.tsx
> +        ...navProps,
@danibonilha passing safeParams on DepotScreen now
https://github.com/cardstack/cardwallet/blob/679bafa627faa206b193ae59d1c3c72178c268d5/cardstack/src/screens/DepotScreen.tsx#L147

2021-11-17 21:05 UTC, merged