[CS-2618]Add merchant payment received sheet
cardstack/cardwallet pull request #583
Opened 2021-12-20 14:45 UTC by topwebtek7

### Description

- [x] Completes #CS-2618

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

![Dec-20-2021 22-43-32](https://user-images.githubusercontent.com/16714648/146785199-a55df02a-9e05-4c14-87b0-f5df0a6bd76d.gif)

2021-12-22 19:20 UTC, lukemelia requested changes
I added a few suggestions as review comments

2021-12-22 19:20 UTC, lukemelia commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
> +            borderRadius={70}
Is 70 a standard for us? Should it be captured as a named constant?

2021-12-22 19:20 UTC, lukemelia commented on src/components/expanded-state/MerchantSpendReceivedExpandedState.tsx
> +    CoinIcon: <CoinIcon size={30} symbol="DAI" />,
Should DAI be hard-coded here? I believe it would be possible for funds to be received as other tokens.

2021-12-22 19:20 UTC, lukemelia commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +      ) ? (
Extract this to a local variable to improve readability.

2021-12-28 18:16 UTC, lukemelia approved these changes
LGTM

2021-12-28 18:47 UTC, topwebtek7 commented
@kdowlin do you want to wait this pr for design change or it's ok to merge for now?

2021-12-28 18:54 UTC, kdowlin commented
<img width="462" alt="Screen Shot 2021-12-28 at 10 53 54 AM" src="https://user-images.githubusercontent.com/42585693/147597924-d4e54de3-988b-49c0-bbdd-e75aa8741f7b.png">
Remove the received spend transaction and it should be good for now.

2021-12-28 18:57 UTC, topwebtek7 commented
ok. btw will wait for #588 to be merged

2022-01-03 20:52 UTC, danibonilha reviewed
There are some improvements to be done, also  @kdowlin agreed on using the `check-circle` icon so no need to add the blue one.

2022-01-03 20:52 UTC, danibonilha commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
> +          </Container>
I have two concerns about this: 
 1. Mixing up the goal of this component which is to only display the MerchantInfo.
 2. Using multiple nested ternaries which is a bit confusing. 

For the first one I get the layout is almost the same, so it would make sense to adapt this one to reuse, but I'd suggest that, instead of having a boolean flag based on the payment, we add a prop called, `iconFallback`, `customIcon` something like that, then
 `<Icon name="user" size={USER_ICON_SIZE} />`  could be replaced with some helper function, `getFallbackIcon` which would render  the `user` icon, or the one received from props, bc we wouldn't have merchantInfo anyway, so the icon would be rendered. This way we can even use this for different scenarios if we need. Ideally if we add the checkmarkCircled icon svg with the right colors already on our side we wouldn't even need the helper function, it would be as simple as  `<Icon name={iconFallbackName || 'user'} size={USER_ICON_SIZE} />`

2022-01-03 20:52 UTC, danibonilha commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
> +import { Icon } from '@rainbow-me/components/icons';
We were using cardstack's Icon component, why change to rainbow's one ? We should actually add the icon svg on our side.

2022-01-03 20:52 UTC, danibonilha commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
>          )}
it would be something like this:
```suggestion
import React, { memo, ReactNode } from 'react';
import { ActivityIndicator } from 'react-native';
import { MerchantInformation } from '@cardstack/types';
import { Container, ContainerProps, Icon, Text } from '@cardstack/components';
import { ContactAvatar } from '@rainbow-me/components/contacts';
import { IconName } from '@cardstack/components/Icon';

interface Props extends ContainerProps {
  merchantInfoDID?: MerchantInformation;
  isLoading?: boolean;
  children: ReactNode;
  iconFallback: IconName;
}

const MerchantSectionCard = ({
  merchantInfoDID,
  children,
  isLoading = false,
  iconFallback,
  ...props
}: Props) => (
  <Container
    backgroundColor="grayCardBackground"
    borderRadius={10}
    padding={8}
    {...props}
  >
    {isLoading ? (
      <Container flex={1} justifyContent="center" alignItems="center">
        <ActivityIndicator />
      </Container>
    ) : (
      <Container alignItems="center">
        {merchantInfoDID ? (
          <ContactAvatar
            color={merchantInfoDID?.color}
            size="xlarge"
            value={merchantInfoDID?.name}
            textColor={merchantInfoDID?.textColor}
          />
        ) : (
          <Icon name={iconFallback || 'user'} size={80} />
        )}
        {merchantInfoDID && (
          <Container paddingTop={3} marginBottom={4}>
            <Text
              weight="extraBold"
              size="medium"
              ellipsizeMode="tail"
              numberOfLines={1}
            >
              {merchantInfoDID?.name || ''}
            </Text>
          </Container>
        )}
      </Container>
    )}
    {children}
  </Container>
);

export default memo(MerchantSectionCard);
```

then just an example with a icon that already exists in the project:

```tsx
   <MerchantSectionCard iconFallback="check-circle">
```

<img width="300" alt="Screenshot" src=https://user-images.githubusercontent.com/20520102/147977422-9d64e426-986d-455e-b39b-b408787952d1.png>

2022-01-03 20:52 UTC, danibonilha commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +  );
I think this is a great opportunity to use the new Sheet component instead of adding on more dependency on the ExpandedAssetState, since this is not an asset, you can check `CollectibleSheet`  for reference.

2022-01-03 20:52 UTC, danibonilha commented on src/components/expanded-state/payment-item-details/PaymentItemDetails.tsx
> +  isPrepaidCard?: boolean;
it's a bit crowded we could create it's own interface

2022-01-03 20:52 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +  props: MerchantTransactionExpandedStateProps & { inlineContent?: boolean }
where is `inlineContent` being used ?

2022-01-03 20:52 UTC, danibonilha commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +        )}
nit: earnedItems could be wrapped on useMemo and return the mapped items

2022-01-04 16:58 UTC, lukemelia requested changes

2022-01-04 16:58 UTC, lukemelia commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +          subText={transactionData.netEarnedNativeDisplay}
Seems weird that we are passing `subText` here as well as in `txRowProps`. Looks like the top level one is not used and can be removed from the props type and from here.

2022-01-04 17:00 UTC, topwebtek7 commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +          subText={transactionData.netEarnedNativeDisplay}
yes, good catch! 👍🏼

2022-01-04 18:40 UTC, danibonilha approved these changes
Looks good overall, just some minor improvements

2022-01-04 18:40 UTC, danibonilha commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
> +          </Container>
We can check just for merchantInfoDID, if `merchantInfoDID` exists we render the name, otherwise we don't, so no need for `isPaymentReceived` flag.

```suggestion
        {!!merchantInfoDID && (
          <Container paddingTop={3} marginBottom={4}>
            <Text
              weight="extraBold"
              size="medium"
              ellipsizeMode="tail"
              numberOfLines={1}
            >
              {merchantInfoDID?.name || ''}
            </Text>
          </Container>
```

2022-01-04 18:40 UTC, danibonilha commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +        item,
why `asset`  and `item`?  Maybe we can merge them and pass it as a single param as `paymentTxDetails` or so.

2022-01-04 18:40 UTC, danibonilha commented on cardstack/src/screens/sheets/PaymentReceived/PaymentReceivedSheet.tsx
> +  });
no need for this in the new sheet

2022-01-04 18:40 UTC, danibonilha commented on cardstack/src/screens/sheets/PaymentReceived/PaymentReceivedSheet.tsx
> +  return useMemo(
the `memo` on the export is enough, we don't need to wrap on useMemo

2022-01-04 18:53 UTC, topwebtek7 commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +        item,
you will see why have asset and item if look at PaymentReceivedSheet. it's almost kind of consistent with other transactions

2022-01-04 18:53 UTC, topwebtek7 commented on cardstack/src/components/TransactionConfirmationSheet/displays/components/sections/MerchantSectionCard.tsx
> +          </Container>
nice catch! just missed it

2022-01-04 18:56 UTC, topwebtek7 commented on src/components/expanded-state/MerchantTransactionExpandedState.tsx
> +          subText={transactionData.netEarnedNativeDisplay}
@lukemelia this is fixed. could you approve so can merge this pr?

2022-01-04 20:29 UTC, danibonilha commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +        item,
I saw the use of asset and item inside, `PaymentReceivedSheet `, still I don't think this name is meaningful since we are not passing a asset, we are actually passing the transaction details, this whole thing of using ExpandedAsset, or anything related to Asset, for other things that are not actual assets, doesn't make much sense, and it would nice to move away from it, that's why I questioned it. Hopefully we can migrate little by little.

2022-01-05 12:57 UTC, topwebtek7 commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +        item,
ok, updated param merged with asset, item. anyway I think we will need to revisit this when handing push notification for received payment.

2022-01-05 17:04 UTC, lukemelia approved these changes
👍  Good to go from my perspective

2022-01-05 17:05 UTC, merged