[CS-2929]: Fix dust amount and migrate unclaimedRevenue
cardstack/cardwallet pull request #599
Opened 2022-01-12 21:37 UTC by danibonilha

### Description
This PR fixes the dust amount and moves the unclaimedRevenue from expandedState, to the new Sheet component. Abstracts the `RouteType` type to be shared across all screens. I wanted to test more on Android, but unable to build right now since Jcenter is out, but the code is good be reviewed already.

- [x] Completes #(CS-2929)

### Screenshots

![Simulator Screen Recording - iPhone 11 - 2022-01-12 at 17 27 05](https://user-images.githubusercontent.com/20520102/149224861-9b461486-3955-4d3e-9567-17bef506a238.gif)

2022-01-12 21:37 UTC, danibonilha commented on cardstack/src/components/TransactionList/TransactionListLoading.tsx
> +  light?: boolean;
This is temporary, we can remove it when we migrate all the conditional sectionLists

2022-01-12 23:03 UTC, lukemelia requested changes

2022-01-12 23:03 UTC, lukemelia commented on src/components/expanded-state/UnclaimedRevenueExpandedState.tsx
> +          <Button disabled={!isDust} marginTop={8} onPress={onClaimAll}>
Something seems off. You should not be able to claim dust, but this logic says the button should be disabled if it is NOT dust.

2022-01-12 23:03 UTC, lukemelia commented on cardstack/src/screens/sheets/UnclaimedRevenue/UnclaimedRevenueSheet.tsx
> +      <Button disabled={!isDust} marginTop={8} onPress={onClaimAll}>
Same here. It should be disabled if there is nothing to claim or only dust to claim.

2022-01-12 23:03 UTC, lukemelia commented on cardstack/src/screens/sheets/UnclaimedRevenue/UnclaimedRevenueSheet.tsx
> +  onClaimAllPress: () => void;
👍  Much better name :)

2022-01-13 14:09 UTC, danibonilha commented on src/components/expanded-state/UnclaimedRevenueExpandedState.tsx
> +          <Button disabled={!isDust} marginTop={8} onPress={onClaimAll}>
my bad, I committed the wrong piece 🤦‍♀️

2022-01-13 14:25 UTC, danibonilha commented on src/components/expanded-state/UnclaimedRevenueExpandedState.tsx
> +          <Button disabled={!isDust} marginTop={8} onPress={onClaimAll}>
`isDust` should be `hasClaimableAmount`, bc on gnosis safe we already check for dustAmount, and if we have one, the native amount is set to zero, so in unclaimedRevenue we check is native amount is a valid value. 
`const hasClaimableAmount = !!nativeAmount` the previous name was misleading as we are not checking for dust anymore

2022-01-13 17:24 UTC, lukemelia approved these changes
🙌  LGTM!

2022-01-13 17:48 UTC, merged