[CS-2616] Add in-app notification handling for merchant payment received
cardstack/cardwallet pull request #605
Opened 2022-01-18 14:18 UTC by topwebtek7

### Description

- [] Completes #CS-2616

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

![Jan-18-2022 22-00-33](https://user-images.githubusercontent.com/16714648/149953638-8f2068b7-28bb-4959-abf2-a1705286d26f.gif)

2022-01-20 13:46 UTC, topwebtek7 commented on cardstack/src/screens/sheets/PaymentReceived/PaymentReceivedSheet.tsx
> +          <PaymentDetailsItem info={fromAddress} isPrepaidCard title="FROM" />
It was showing wrong `from` address, so fixed it

2022-01-20 13:46 UTC, topwebtek7 commented on cardstack/src/notification-handler/merchantPrepaidCardPaymentReceived.tsx
> +};
It's mapping transaction data to render Payment Received sheet

2022-01-20 13:46 UTC, topwebtek7 commented on cardstack/src/notification-handler/index.ts
> +    }
Add title to local notification as hub had no title mostly(It shows just `CardWallet` as title cause remote notification)

2022-01-20 14:54 UTC, danibonilha requested changes
We need to drop the ios certificate/provising-profile changes, other than that it's looking good I just need to test it, I'll ask for @gabiburger 's help on that

2022-01-20 14:54 UTC, danibonilha commented on ios/Rainbow.xcodeproj/project.pbxproj
>  				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
We need to drop this file change, it will break the CI builds

2022-01-20 14:54 UTC, danibonilha commented on cardstack/src/components/Transactions/Merchant/MerchantEarnedSpendAndRevenueTransaction.tsx
> +}) => (
nit: we could extract this to it's own interface to improve readability

2022-01-20 14:54 UTC, danibonilha commented on cardstack/src/notification-handler/index.ts
> +  'merchant_claim' = 'merchant_claim',
nit: maybe we could use camelCase for the enum key to match other patterns

2022-01-20 14:54 UTC, danibonilha commented on cardstack/src/notification-handler/index.ts
> +export const displayLocalNotification = async (notificationData: any) => {
Is there a way to know the `notificationData` type ? To avoid using any

2022-01-20 14:54 UTC, danibonilha commented on cardstack/src/notification-handler/index.ts
> +    }
Taking into consideration we need to check the notificationType on `notificationHandler` and then again on `displayLocalNotification` and we might want to add diff titles for diff types, maybe using object literals is more reusable than using switch/case.

e.g.

```ts
import notifee from '@notifee/react-native';
import { merchantPrepaidCardPaymentReceivedHandler } from './merchantPrepaidCardPaymentReceived';
import logger from 'logger';

interface NotificationDataType {
  notificationType: NotificationType;
  transactionInformation: string;
}

interface NotificationInfoType {
  data: NotificationDataType;
  body: string;
}

// add more notification types here
export enum NotificationType {
  customerPayment = 'customer_payment',
  merchantClaim = 'merchant_claim',
}

interface NotificationConfig {
  title: string;
  handler: (data?: NotificationDataType) => void;
}

const notificationConfig: Record<NotificationType, NotificationConfig> = {
  [NotificationType.customerPayment]: {
    title: 'Payment Received',
    handler: data => {
      if (!data?.transactionInformation) return;
      // parse to object as hub sends data as a string
      const { transactionInformation } = data;
      const transactionData = JSON.parse(transactionInformation);
      merchantPrepaidCardPaymentReceivedHandler(transactionData);
    },
  },
  [NotificationType.merchantClaim]: {
    title: '',
    handler: () => {
      console.log('merchantClaimHandler');
    },
  },
};

export const notificationHandler = ({ data }: NotificationInfoType) => {
  const { notificationType } = data;

  if (notificationType) {
    notificationConfig?.[notificationType]?.handler(data);
  }
};

interface LocalNotificationDataType {
  notification: { title?: string; body: string };
  data: NotificationDataType;
}

export const displayLocalNotification = async (
  notificationData: LocalNotificationDataType
) => {
  try {
    const {
      notification: { title, body },
      data,
    } = notificationData;

    const { notificationType } = data;

    // update notification title when no title from hub side(mostly had no title)
    const notificationTitle =
      title || notificationConfig?.[notificationType]?.title || '';

    await notifee.displayNotification({
      title: notificationTitle,
      body,
      data,
    });
  } catch (e) {
    logger.sentry('Display LocalNotification failed - ', e);
  }
};

```
But it's just a diff approach, feel free to ignore, we could also ask for the hub team to always send a title, then we wouldn't need to worry about this here

2022-01-20 14:54 UTC, danibonilha commented on src/screens/ChangeWalletSheet.js
> +
nit: we could extract this to it's own function

2022-01-20 14:55 UTC, topwebtek7 commented on ios/Rainbow.xcodeproj/project.pbxproj
>  				GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
oh got it

2022-01-20 14:59 UTC, topwebtek7 commented on cardstack/src/notification-handler/index.ts
> +  'merchant_claim' = 'merchant_claim',
basically it's notification key sent from hub side, gonna discuss moving to sdk

2022-01-20 20:45 UTC, danibonilha commented
With the app on background or closed, when I get a payment/merchant claim/wallet connect notification and tap on it,  I get a crashing bug: 
```
 ERROR  TypeError: undefined is not an object (evaluating 'data.notificationType')
```

With the app open, payment notification works as expected.

2022-01-21 15:33 UTC, topwebtek7 commented
> @topwebtek7 With the app on background or closed, when I get a payment/merchant claim/wallet connect notification and tap on it, I get a crashing bug:

ok, fixed this issue

2022-01-24 17:03 UTC, lukemelia commented
@topwebtek7 it looks like there are a number of comments that Dani left in her review that you have not responded to or resolved. Can you do that before we proceed with this?

2022-01-25 21:05 UTC, danibonilha approved these changes
It's looking good, I just left a couple of suggestions, from what I was able to test on iOS, the only thing that didn't work properly, was opening the merchant claim notification with the app closed, my guess is it didn't work bc we need to wait to have safes info bf navigating, but I think we can merge this one and open a bug ticket for this specific case.

2022-01-25 21:05 UTC, danibonilha commented on cardstack/src/models/firebase.ts
> +    ) {
```suggestion
    if (fcmToken && addressesByNetwork?.[network]?.includes(address)) {
```

2022-01-25 21:05 UTC, danibonilha commented on cardstack/src/models/firebase.ts
> +      if (unregisterResponse && unregisterResponse.success) {
```suggestion
      if (unregisterResponse?.success) {
```

2022-01-25 21:05 UTC, danibonilha commented on cardstack/src/notification-handler/index.ts
> +      logger.log('merchantClaim notif--', data);
typo maybe ?

2022-01-25 21:05 UTC, danibonilha commented on cardstack/src/notification-handler/index.ts
> +  }
```suggestion
  if (data?.notificationType) {
    const { notificationType } = data;

    notificationConfig?.[notificationType]?.handler(data);
  }
  ```

2022-01-26 04:33 UTC, merged