[CS-3179] Add CreateProfile step one
cardstack/cardwallet pull request #688
Opened 2022-03-08 17:08 UTC by topwebtek7

### Description

Created first step of profile component and adding steps indicator in another pr

- [CS-3179] Completes #(Linear ticket)

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

<img width="370" alt="image" src="https://user-images.githubusercontent.com/16714648/157288708-61a34db9-3055-42ae-bef9-cb94bdd9141e.png">

2022-03-08 19:33 UTC, oidoug reviewed
Looks good, but better refactor CreateProfileStepOne out of ProfileScreen before merging.

2022-03-08 19:33 UTC, oidoug commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +  const CreateProfileStepOne = () => (
It would be better to have this component in a separate file. We'll have a few steps like this in the end.

2022-03-08 19:33 UTC, oidoug commented on cardstack/src/components/MerchantSafe/MerchantSafe.tsx
> +  const PressableContainer = notPressable ? Container : CardPressable;
I think you can use CardPressable disabled prop instead of switching for a container here.
If the style doesn't match up, maybe adapt CardPressable to work as you expect by redefining onPress.

notPressable could also be just disabled, although disabled sometimes also implies a different style, so I'm not sure.

2022-03-08 19:51 UTC, danibonilha reviewed
It seems the design of the "merchantSafe" has changed, it's worth checking if the updated layout is expected in this task @kdowlin

2022-03-08 19:51 UTC, danibonilha commented on cardstack/src/components/MerchantSafe/MerchantSafe.tsx
> +
Instead of conditionally  choose the container, couldn't we simply use the disabled prop on `<CardPressable>` ? We could receive `disabled` as prop and pass down instead of using `notPressable` then we don't have to check anything in other to pass `onPress`

2022-03-08 19:51 UTC, danibonilha commented on cardstack/src/components/MerchantSafe/MerchantSafe.tsx
> +          rightText={notPressable ? 'Profile' : undefined}
nit: Here we could receive the `rightText` as a prop, `HeaderRightText` which could default to 'Profile'

2022-03-08 19:51 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +  }, [currencyConversionRates, nativeCurrency, network]);
There's a type on this function name, but it also seems we don't need this, what is the intention ?

2022-03-08 19:51 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +  );
This screen uses fixed padding etc, instead of flex,  it doesn't seem to work right on smaller devices 
<img width="200" alt="image" src="https://user-images.githubusercontent.com/20520102/157311172-e2ca9644-0e87-4a58-a119-f6e9f7f538dc.png">
We could think about adding a scrollView, but I think scaling the components based on the phone available space to flex might be better

2022-03-08 19:51 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/fixture.ts
> +};
fixture is usually more related to testing suite, let's keep these type of files, either as strings, os as utils

2022-03-09 13:15 UTC, topwebtek7 commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +  }, [currencyConversionRates, nativeCurrency, network]);
nice catch. these are required in MerchantSafe component, so updated with empty data except networkName which is  correct current network name.

2022-03-09 19:00 UTC, oidoug approved these changes
👍

2022-03-09 19:00 UTC, oidoug commented on cardstack/src/components/MerchantSafe/MerchantSafe.tsx
> +  notPressable?: boolean;
nit: isn't disabled a better term, since we're using disabled on cardpressable too?

2022-03-09 19:00 UTC, oidoug commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +        {primarySafe ? <MerchantSafe {...primarySafe} /> : <CreateProfile />}
nit: primarySafe could be double-negated (`!!primarySafe`), but doest mather much, I'll need to change this a bit later to merge PR #691 with it.

2022-03-09 20:30 UTC, danibonilha requested changes
Nice adaptation to support smaller devices, but there's still some things to address:
- wrong backgroundColor
- removal of exampleMerchantExtraProps 
- using disabled as the pattern

2022-03-09 20:30 UTC, danibonilha commented on cardstack/src/components/MerchantSafe/MerchantSafe.tsx
> +  notPressable?: boolean;
Agreed on rename it to disabled

2022-03-09 20:30 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/ProfileScreen.tsx
> +        {primarySafe ? <MerchantSafe {...primarySafe} /> : <CreateProfile />}
We just need to cast to boolean if the assertion is boolean e.g `primarySafe && <Merchant>`, bc if primarySafe is a `positive` value, like a string for example, it will try to render as a "component", another way to prevent something like that would be to use `primarySafe ? <Merchant>: null`
in case of the ternary it's okay not to cast, since the default case will be to render the `<CreateProfile>`

2022-03-09 20:30 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/components/CreateProfileStepOne.tsx
> +  }, [network]);
As I've mentioned before, it doesn't seem we need this, if your branch is up-to-date with develop, you'll noticed those props were removed

2022-03-09 20:30 UTC, danibonilha commented on cardstack/src/screens/ProfileScreen/components/CreateProfileStepOne.tsx
> +      backgroundColor="black"
Why is the background black ? I think it's supposed to be the same as the other tabs, darkPurple
<img width="295" alt="image" src="https://user-images.githubusercontent.com/20520102/157530183-7a0f24f7-efcf-4476-b192-200b375eb406.png">

2022-03-10 11:02 UTC, topwebtek7 commented on cardstack/src/screens/ProfileScreen/components/CreateProfileStepOne.tsx
> +      backgroundColor="black"
oh i've added it for UI check purpose and forgot to remove, good catch!

2022-03-10 12:30 UTC, danibonilha approved these changes
LGTM

2022-03-10 13:58 UTC, merged