[CS-3459] Add color picker modal in create profile flow
cardstack/cardwallet pull request #734
Opened 2022-03-25 14:20 UTC by topwebtek7

### Description

Added color picker modal behavior in create profile flow and did some clean up.

- [x] Completes #CS-3459

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

![Mar-25-2022 22-12-52](https://user-images.githubusercontent.com/16714648/160138573-3dacc71b-5982-4309-b0c9-58ae72f185c1.gif)

2022-03-25 15:01 UTC, oidoug approved these changes
The picker UI is pretty cool!
Just a small nit.

2022-03-25 15:01 UTC, oidoug commented on cardstack/src/screens/ColorPickerModal.tsx
> +  const onSelect = () => {
nit: wrap on useCallback

2022-03-25 15:30 UTC, danibonilha requested changes
It's broken on android and on smaller devices

<img width="500" alt="image" src="https://user-images.githubusercontent.com/20520102/160151496-b7146faa-9be1-4a82-969a-f3f5e1771188.png">

2022-03-25 15:30 UTC, danibonilha commented on cardstack/src/screens/ColorPickerModal.tsx
> +        </Container>
Doesn't using `<Sheet scrollEnabled={false} />` as the container works for this case?

2022-03-28 07:26 UTC, topwebtek7 commented
Fix ui in android, iphone SE
<img width="353" alt="Screen Shot 2022-03-28 at 15 24 13" src="https://user-images.githubusercontent.com/16714648/160347344-20e3ebc0-3233-43e0-995d-cb520f791e39.png">
<img width="333" alt="Screen Shot 2022-03-28 at 15 24 02" src="https://user-images.githubusercontent.com/16714648/160347358-dd373bd7-9a04-4392-b793-292ccda4dec1.png">
<img width="357" alt="Screen Shot 2022-03-28 at 15 23 25" src="https://user-images.githubusercontent.com/16714648/160347360-0994d9e0-4740-4bf9-ac3f-bdc6b86e505c.png">

2022-03-28 07:27 UTC, topwebtek7 commented on cardstack/src/screens/ColorPickerModal.tsx
> +        </Container>
cool, updated with Sheet component

2022-03-28 13:47 UTC, danibonilha approved these changes
LGTM

2022-03-28 13:51 UTC, merged