[CS-3418] Update ChoosePrepadCard to support custom payCostDesc
cardstack/cardwallet pull request #738
Opened 2022-03-28 12:48 UTC by topwebtek7

### Description

Added `payCostDesc` prop to `CHOOSE_PREPAIDCARD_SHEET` screen to support custom pay cost description

- [x] Completes #CS-3418

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

2022-03-28 13:51 UTC, danibonilha commented
@topwebtek7 can you add the "To pay transaction amount cost" to the rewards flow ?  That's the main goal of this task

2022-03-28 15:14 UTC, topwebtek7 commented
> @topwebtek7 can you add the "To pay transaction amount cost" to the rewards flow ? That's the main goal of this task

@danibonilha Updated it, could you confirm on your side as I don't have rewards on my wallets?

2022-03-28 16:10 UTC, danibonilha commented
> > @topwebtek7 can you add the "To pay transaction amount cost" to the rewards flow ? That's the main goal of this task
> 
> @danibonilha Updated it, could you confirm on your side as I don't have rewards on my wallets?

The font size seems too big 

<img width="400" alt="image" src="https://user-images.githubusercontent.com/20520102/160440575-9d8b076b-c1e0-45b2-83df-4b9bd3e69926.png">

Also we can test it even without rewards, just replace the hooks flag with
```ts
  const isRegistered = false;
  const hasRewardsAvailable = true;
```
and comment out `mainPoolRowProps` on ` <RegisterContent`

2022-03-28 21:06 UTC, oidoug approved these changes
LGTM

2022-03-28 21:19 UTC, oidoug requested changes
Sorry Brian, it seems the font size should be corrected. I didn't notice the comments.

2022-03-29 06:04 UTC, topwebtek7 commented
<img width="300" alt="Screen Shot 2022-03-29 at 14 00 55" src="https://user-images.githubusercontent.com/16714648/160544042-7623edf9-952c-4aa5-aac2-6b657240f436.png">

2022-03-29 13:50 UTC, danibonilha approved these changes
LGTM

2022-03-29 13:54 UTC, oidoug approved these changes
Sorry to hold it off, all good!

2022-03-29 13:54 UTC, merged